AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.8
      CodeUri: src/
      Role: arn:aws:iam::123456789012:role/cessao-fundo-lambda-role
      Timeout: 300
      Events:
        S3Put:
          Type: S3
          Properties:
            Bucket: cession-fundo-bucket
            Events: s3:ObjectCreated
